### ISSUE TITLE
WSA won't load in/booting at all, it always closing after displaying starting windows subsystem for android.

### ISSUE THREAD

**Issue by tfragment** [LSPosed/MagiskOnWSA#68]
As you can see on the title, I already tried so many times re-installing the wsa.. but it still nothing. it didn't even show any errors or responds, it's just nothing yeah nothing. Man.. I hope someone can help me with this :(.

Hyper-V: Check
Virtual Machine Platforms: Check
Windows Hypervisor Platforms: Check
Virtualization: Enabled
Microsoft.UI.Xaml.2.6: Installed
Microsoft.VCLibs.140.00.UWPDesktop: Installed
Microsoft.VCLibs.140.00: Installed

**Comment by yujincheng08** [comment]
fixed

**Comment by tfragment** [comment]
I've just found out that github only let me download the artifact in half size, like about 900MB when the original file size is about 2.0GB. This is weird... I even tried downloading it through vps. and it still won't let me download fully of the file artifact.

[https://github.com/tfragment/MagiskOnWSA/actions/runs/1449313916](https://github.com/tfragment/MagiskOnWSA/actions/runs/1449313916)

**Comment by tfragment** [comment]
https://user-images.githubusercontent.com/93957774/141336937-42ef1993-53af-42c9-86d1-1fa96cd98180.mp4

**Comment by yujincheng08** [comment]
>  Artifact.mp4

Expected. The size shown in Github is the uncompressed size and the size you download is the compressed size.

**Comment by tfragment** [comment]
I see, i thought it was the cause. Thanks for the explanation.

**Comment by tfragment** [comment]
Yes, it's still like this... wsa won't run at all... and yes, I've waited and waited for the menu to pop up, but alas, nothing is popping up. 
https://user-images.githubusercontent.com/93957774/141680834-8be47876-cab2-4a6b-a185-270453949581.mp4

**Comment by chaoscreater** [comment]
Still an issue.
